title: Footnote Consults Ltd
description: "Footnote Consults Ltd - Engineering the future."
baseurl: "" # Set to "/your-github-username.github.io/" if using GitHub Pages
url: "https://footnoteconsults.com/" # Your website's URL
theme: null # No theme used, we'll use custom Bootstrap
# _config.yml
client_separator: <!--more-->



# Plugins (Optional)
# plugins:
#   - jekyll-seo-tag
#   - jekyll-feed
